### ISSUE TITLE
encrypt file

### ISSUE THREAD

**Issue by TKR-US** [caml-pkcs11/opkcs11-tool#1]
Hi,

i'm not sure it's possible to use "-enc" to encrypt a file (10 Mo for example) with a symmetric key.

i generate a aes key with "-keygen -mech aes -keysize 128 -id 1 -label aeskey.

i looked your source code, and see only asymmetric encryption (to encrypt an aes key for example)

**Comment by rb-anssi** [comment]
Hi. It should be possible to encrypt some data with a symmetric key, since we accept any mechanism in C_EncryptInit. Have you managed to do it since the issue is closed or do you still need some help?

**Comment by bzh35** [comment]
Hi.

The problem is about the size of file i want to Encrypt, i don't know why...
For testing, i can't encrypt a file less than 3 mo (cKR_DATA_LEN_RANGE), and i have an out of memory when i  try 100 Mo.

Is there a possibility to extract the pubkey with opkcs11-tool ?
i try command like :
root@ubuntu:~# /usr/local/bin/opkcs11-tool -module /usr/lib/pkcs11/PKCS11_API.so -l -pin 1234 -c -search-attributes "CKA_CLASS=CKO_PUBLIC_KEY" -verbose -out /tmp/test

without success (no error, but no output)

**Comment by bzh35** [comment]
mhh... -c, copy object :)

So, is there a possibility to extract my key into a file, as pkcs11-tool can do it?

**Comment by rb-anssi** [comment]
Hi,

1) Regarding the cKR_DATA_LEN_RANGE error you get on some files, please beware that depending on the mechanism you choose, some length constraints may exist on the input file size. For instance, CKM_AES_ECB expects an input of size multiple of 16 bytes (one AES block), and will give this error if this is not the case. I have successfully encrypted a small file of size 32 bytes with an AES secret key. Other mechanisms allow padding when not aligned on a block size (for instance CKM_AES_CBC_PAD), but they expect other inputs as parameters  (initialization vectors, ...).
2) Regarding the cKR_KEY_TYPE_INCONSISTENT you get with your RSA key pair, this might be related to the mechanism you are trying to use to encrypt. Please try to use CKM_RSA_PKCS for instance (I have just tried it with a 4096 RSA public key on a small file, and it works).
3) Regarding the "CKA_ENCRYPT FALSE" for the key you get after a key pair generation, this completely depend on the default behavior of you token. You can fine tune the generation of public and private templates with the "-pub-attributes" and "-priv-attributes" on the command line. In your case, you want a -pub-attributes "CKA_ENCRYPT=TRUE".
4) Regarding the key values extraction from the token, the "-c" (copy) option is not what you seek. This option triggers a PKCS#11 C_CopyObject call that creates a new object *inside the token* that is the copy of an existing one. For now, there is no direct way to extract keys that are inside the token (meaning in their DER ASN.1 binary format as expected by other tools such as openssl). Of course, beware that you won't be able to extract CKA_SENSITIVE=TRUE private and secret keys!
==> However, the attributes "dumped" by opkcs11-tool should be enough information to create the key with dedicated tools handling ASN.1/DER. By the way, are you sure pkcs11-tool is able to extract objects from tokens?
